### ISSUE TITLE
Scan IMAP Subfolders

### ISSUE THREAD

**Issue by apographon** [polo2ro/imapbox#13]
Any chance to have imapbox to crawl all Subdirectories?

**Comment by polo2ro** [comment]
it's probably possible, for now I'd like the remote_folder option to process a list of folders. We could make sure to take the subfolders at the same time.

**Comment by Maurice-Mueller** [comment]
I added a pull request which will do exactly this thing. Please see #21

**Comment by polo2ro** [comment]
#21 is merged
