### ISSUE TITLE
Archiving of subfolders fails

### ISSUE THREAD

**Issue by viegelinsch** [polo2ro/imapbox#25]
Hi,
I get the following Error

> account1/__ALL__ (on fqdn.domain.com)
> Saving folder: Calendar
> 0 emails created, 0 emails already exists
> Saving folder: Contacts
> 0 emails created, 0 emails already exists
> Saving folder: Drafts
> 0 emails created, 1 emails already exists
> Saving folder: INBOX
> 0 emails created, 3 emails already exists
> Saving folder: INBOX.Archiv
> Traceback (most recent call last):
>   File "imapbox.py", line 98, in <module>
>     main()
>   File "imapbox.py", line 93, in main
>     save_emails(account, options)
>   File "/Users/henegger/git/imapbox/mailboxresource.py", line 109, in save_emails
>     stats = mailbox.copy_emails(options['days'], options['local_folder'], options['wkhtmltopdf'])
>   File "/Users/henegger/git/imapbox/mailboxresource.py", line 36, in copy_emails
>     typ, data = self.mailbox.search(None, criterion)
>   File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imaplib.py", line 723, in search
>     typ, dat = self._simple_command(name, *criteria)
>   File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imaplib.py", line 1196, in _simple_command
>     return self._command_complete(name, self._command(name, *args))
>   File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imaplib.py", line 944, in _command
>     ', '.join(Commands[name])))
> imaplib.error: command SEARCH illegal in state AUTH, only allowed in states SELECTED`

Any idea how to fix this?

**Comment by olajep** [comment]
Is this an outlook/exchange server?

**Comment by viegelinsch** [comment]
No, the product is called: "CommuniGate® Pro" https://communigate.com/communigatepro/

> Is this an outlook/exchange server?

**Comment by olajep** [comment]
Ok, so maybe this is common among IMAP servers and the comment in #26 is slightly wrong.
Either way it's merged into master and should fix your issue. You might want to use it together with
```
remote_folder=__ALL__
```
in the config file.

**Comment by viegelinsch** [comment]
Worked like a charm! Thank you a lot!

Btw. got a lot 
> MailboxClient.saveEmail() failed: None
but export seems to be complete.

Thanks!
