### ISSUE TITLE
Can't backup anyhting with docker image

### ISSUE THREAD

**Issue by alpham8** [polo2ro/imapbox#33]
Hi,

I cloned the project using `git clone https://github.com/polo2ro/imapbox.git` into the folder `/home/thomas/Projekte/imapbox`.

Then I ceated the config file into `/home/thomas/.config/imapbox/config.cfg`:
```
[imapbox]
local_folder=/home/thomas/mailbackup
days=2

[GMXKonto]
host=imap.gmx.net
username=user.name@gmx.de
password=asdf
remote_folder=__ALL__
port=993
```
The `docker-compose.yml` file accordingly:
```
version: '3'
services:

  imapbox:
    image: mauricemueller/imapbox
    container_name: imapbox
    volumes:
      - imapbox_data:/var/imapbox
      # change the path to the config
      - /home/thomas/.config/imapbox/config.cfg:/etc/imapbox/config.cfg

volumes:
  imapbox_data:
```
After everything was set up, I created the base folder (`mkdir /home/thomas/mailbackup`).

I tried variations of the account name, but some special chars seems not to be the problem here. To run it using docker-compose I did exactly the same as described in readme file:
```
thomas@linux:~/Projekte/imapbox> docker-compose run --rm imapbox
Creating imapbox_imapbox_run ... done
GMXKonto/__ALL__ (on imap.gmx.net)
Traceback (most recent call last):
  File "/opt/bin/imapbox.py", line 98, in <module>
    main()
  File "/opt/bin/imapbox.py", line 91, in main
    print("Saving folder: " + folder_name[1])
IndexError: list index out of range
```

Also, the experiments with only `INBOX` key in config file throws errors:
```
thomas@linux:~/Projekte/imapbox> docker-compose run --rm imapbox
Creating imapbox_imapbox_run ... done
GMX Konto/INBOX (on imap.gmx.net)
/home/thomas/mailbackup/2021/5055368007.37200749.08360958643149newsletter.aljazeera.com
MailboxClient.saveEmail() failed
Expected object of type bytes or bytearray, got: <class 'str'>
12 emails created, 0 emails already exists
```

Even though I got success messages in every experiment, the folder was always empty:
```
thomas@linux:~/Projekte/imapbox> ls -lha /home/thomas/mailbackup/
insgesamt 0
drwxr-xr-x 1 thomas users   0 13. Feb 22:58 .
drwxr-xr-x 1 thomas users 912 13. Feb 22:58 ..
```

The pyhton version on the host system is `Python 2.7.18`. But, as I got it right, this fact doesn't matter, because it's everything set up in the containers.
Host's os-release:
```
thomas@linux:~/Projekte/imapbox> cat /etc/os-release
NAME="openSUSE Tumbleweed"
# VERSION="20210210"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20210210"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20210210"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo"
```

The error for `__ALL__` seems like an array out of max index size exception in console's printing message. But I'm not familar with python - just a quick suggestion of what the error message says.

Any help would be great :-)

Thank you in advice,

alpham8

**Comment by Maurice-Mueller** [comment]
The docker image was out dated. I just gave it an update. So you can try again and see if it works now.

**Comment by Maurice-Mueller** [comment]
My bad, this issue is not 5 days old, but 1 year and 5 days. We should just close this issue @polo2ro
