### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by slaecker** [polo2ro/imapbox#5]
Hi,

I get an error when launching the script.

```
$ python imapbox.py
Traceback (most recent call last):
  File "/opt/git/imapbox/imapbox.py", line 5, in <module>
    from mailboxresource import MailboxClient
  File "/opt/git/imapbox/mailboxresource.py", line 84
    print directory
                  ^
SyntaxError: Missing parentheses in call to 'print'
```

```
$ python --version
Python 3.6.1
```

**Comment by polo2ro** [comment]
Hi unfortunately, imapbox is not compatible with python 3, you can try python2 imapbox.py if python3 has been set as default on your system

**Comment by slaecker** [comment]
Thanks @polo2ro 
Maybe you should note that inside the README.md ;)

So launching with Python 2 I get the following:
```
$ python2 imapbox.py 
Traceback (most recent call last):
  File "imapbox.py", line 5, in <module>
    from mailboxresource import MailboxClient
  File "/opt/git/imapbox/mailboxresource.py", line 8, in <module>
    from message import Message
  File "/opt/git/imapbox/message.py", line 13, in <module>
    import chardet
ImportError: No module named chardet
```

```
$ python2 --version
Python 2.7.13
```

Maybe worth noting: I am running this on an ARM device (Raspberry Pi 3).

**Comment by polo2ro** [comment]
Yes, i need to improve the readme. also because you second error is a dependency error "ImportError: No module named chardet"
you can try "pip2 install chardet" to install the dependency or maybe "apt install python-chardet" on a debian system.
I use this script on my QNAP NAS, i think this is ARM

**Comment by slaecker** [comment]
Thanks, installing python2-chardet did the trick. Now the script runs fine.
